name: Extract ZIP File

on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip file
        run: |
          mkdir -p extracted_files
          unzip Multi-Hospital.zip -d extracted_files
